hikari-demo:
  datasource:
    test-db-1:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://127.0.0.1:3306/test_db_1
      username: root
      password: 123456
    test-db-2:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://127.0.0.1:3306/test_db_2
      username: root
      password: 123456
server:
  port: 8666